version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - ./accounts/:/usr/src/accounts/ 
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=mydatabase
volumes:
  postgres_data:

